language: go
go:
  - 1.14.x

branches:
  only:
    - master

before_install:
  - sudo apt-get install --yes lsof util-linux

# Don't test vendor directory (go test ./... will test these by default and fsnotify causes problems)
script:
  - go test . ./server ./client ./server/auth ./server/keydb ./log

notifications:
  email:
    recipients:
    - devinlundberg@pinterest.com
    on_success: never
    on_failure: change
env:
  global:
    - GO15VENDOREXPERIMENT=1
